# Generated by Django 5.0.3 on 2025-11-15 10:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField()),
                ('about_text', models.TextField()),
                ('placements_percentage', models.CharField(default='95%', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('state', models.CharField(choices=[('andhra', 'Andhra Pradesh'), ('bihar', 'Bihar'), ('goa', 'Goa'), ('maharashtra', 'Maharashtra'), ('tamil', 'Tamil Nadu'), ('karnataka', 'Karnataka'), ('delhi', 'Delhi'), ('other', 'Other')], max_length=20)),
                ('course', models.CharField(max_length=200)),
                ('intake', models.CharField(choices=[('jan', 'January'), ('apr', 'April'), ('jul', 'July'), ('oct', 'October')], max_length=10)),
                ('brochure_required', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='universities.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(default='2 years', max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.university')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'Campus Facilities',
            },
        ),
    ]
